[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"

[build]
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

# Config for the Netlify Build Plugin: netlify-plugin-minify-html
[[plugins]]
  package = "netlify-plugin-minify-html"
  package = "netlify-plugin-amp-server-side-rendering"
  package = "netlify-plugin-no-more-404"

  # Specify which deploy contexts we'll minify HTML in.
  # Supports any Deploy Contexts available in Netlify.
  # https://docs.netlify.com/site-deploys/overview/#deploy-contexts
  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]
     # either "warn" or "error"
     on404 = "error"
     # change this key to a new one any time you need to restart from scratch
     cacheKey = "MyCacheKey"
     # (for development) turn true for extra diagnostic logging
     debugMode = false

  # Optionally, override the default options for the minification
  # https://github.com/kangax/html-minifier#options-quick-reference
  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = false
